<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tingkat Pendidikan_TingkatPendidikannama</name>
   <tag></tag>
   <elementGuidId>ad88fd5a-4ae0-4e94-ae5c-a3471e1c27c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tingkatpendidikan-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tingkatpendidikan-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4bb6b0a-8c54-46fa-9338-2526733bff90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26bd8e3d-e821-4532-8d08-17a4e4416cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tingkatpendidikan-nama</value>
      <webElementGuid>c18c658c-00f6-45e8-9c1d-3a093b4253d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3b43c78c-dc76-44f2-aa6d-c5b9b5aeea5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TingkatPendidikan[nama]</value>
      <webElementGuid>a9a8d158-1b8b-4aff-9236-e4a859770cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AT_001</value>
      <webElementGuid>33569bd8-92fa-4681-a58e-043757df22e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>623c58f7-bce7-440f-b0ea-2e1c6765d9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d16acaf-954e-463d-beef-7526d4aae6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tingkatpendidikan-nama&quot;)</value>
      <webElementGuid>6868f65e-9682-4e82-a129-b44392ba6ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tingkatpendidikan-nama']</value>
      <webElementGuid>703a541c-8b06-4f5c-8a42-ef2ed0767640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/input</value>
      <webElementGuid>23261986-2c88-4d6d-b377-65d8e761c594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b503743a-de4b-4045-be91-4c9b90637e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tingkatpendidikan-nama' and @name = 'TingkatPendidikan[nama]']</value>
      <webElementGuid>7ff6107a-9b6a-49dc-9b22-4d96c2ac327b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
