<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tingkat Pendidikan_TingkatPendidikannama</name>
   <tag></tag>
   <elementGuidId>9f8dce2b-883a-477f-ad71-c1bf42064e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tingkatpendidikan-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tingkatpendidikan-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03a9886a-7b91-43e9-b3bc-3699ab92efe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74a72dbe-c048-41e1-b85e-96c51e2328cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tingkatpendidikan-nama</value>
      <webElementGuid>df3f83b7-2e0d-4df5-8f0f-c67b287f8773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11f800b2-d696-4793-a045-cedc675c557d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TingkatPendidikan[nama]</value>
      <webElementGuid>264e3648-00fd-4004-bcee-109b32614ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b8e30424-bf2d-449e-b581-80768ee78e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bed1cd0d-5ad5-47be-be52-bbd12c5ff685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tingkatpendidikan-nama&quot;)</value>
      <webElementGuid>997310c1-904e-4b62-9f71-28177d48976c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tingkatpendidikan-nama']</value>
      <webElementGuid>fcc4a24e-e6be-46a6-a49f-a77e34c2fb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/input</value>
      <webElementGuid>f4aabf94-748f-4317-832c-592b203a5a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0f8f3db6-6a80-4995-a231-dcc036fcdd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tingkatpendidikan-nama' and @name = 'TingkatPendidikan[nama]']</value>
      <webElementGuid>bc2f153e-5630-4b31-88f3-dbd6ac50f76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
