<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345678</name>
   <tag></tag>
   <elementGuidId>795f8e64-2235-4617-ae63-de02d19a19aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aktivitas-durasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='aktivitas-durasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Durasi (Jam)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b62df7e6-650f-432a-b5c0-76e77205e559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aktivitas-durasi</value>
      <webElementGuid>ea26c561-1eb2-4213-9419-ddec6b2ac13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9eecbb85-4603-4836-94a2-ed7bca246d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Aktivitas[durasi]</value>
      <webElementGuid>028fa7f9-f093-4404-8a67-1cddd177164f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678</value>
      <webElementGuid>f626e86c-e6f7-455a-aafd-4de81a2c966d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aktivitas-durasi&quot;)</value>
      <webElementGuid>abc37041-ba28-4922-a16c-7e81932a030e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='aktivitas-durasi']</value>
      <webElementGuid>9da8f3ee-d5d2-4062-bc8b-c1e5903426c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[2]/div/select</value>
      <webElementGuid>c809c497-82c0-4698-993b-6718805dc888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Durasi (Jam)'])[1]/following::select[1]</value>
      <webElementGuid>7197ec10-b36a-44f5-ae5f-a62cfb16e505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/following::select[1]</value>
      <webElementGuid>1e775015-4d5a-4736-b220-e753601dff7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Aktivitas'])[1]/preceding::select[1]</value>
      <webElementGuid>6dd3cae3-656f-438b-9fe9-ad04dc452157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Aktivitas'])[1]/preceding::select[2]</value>
      <webElementGuid>4949bcd1-5158-4b5e-a6de-8b98dfdb082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>68974519-2c5f-450e-a246-7ddc5fb4aa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'aktivitas-durasi' and @name = 'Aktivitas[durasi]' and (text() = '12345678' or . = '12345678')]</value>
      <webElementGuid>e9edb457-a5c2-450b-b5b7-284206a652b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
